version: '3.8'

services:
  pdf-query-pro-backend:
    image: pdf-query-pro-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - PORT_PROD: ${{ vars.PORT_PROD }}
      - PORT_DEV: ${{ vars.PORT_DEV }}
      - SECRET_KEY: ${{ secrets.SECRET_KEY }}
      - ALGORITHM: ${{ secrets.ALGORITHM }}
      - ACCESS_TOKEN_EXPIRES_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRES_MINUTES }}
      - AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      - AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - AWS_BUCKET_NAME_DEV: ${{ vars.AWS_BUCKET_NAME_DEV }}
      - AWS_REGION_TEST: ${{ vars.AWS_REGION_TEST }}
      - PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      - PINECONE_INDEX: ${{ vars.PINECONE_INDEX }}
      - OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - PINECONE_VECTOR_DIMENSION: ${{ vars.PINECONE_VECTOR_DIMENSION }}
      - RDS_POSTGRESQL_PASSWORD: ${{ vars.RDS_POSTGRESQL_PASSWORD }}