version: '3.8'

services:
  pdf-query-pro-backend:
    image: pdf-query-pro-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT_PROD=${PORT_PROD}
      - PORT_DEV=${PORT_DEV}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRES_MINUTES=${ACCESS_TOKEN_EXPIRES_MINUTES}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME_DEV=${AWS_BUCKET_NAME_DEV}
      - AWS_REGION_TEST=${AWS_REGION_TEST}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_VECTOR_DIMENSION=${PINECONE_VECTOR_DIMENSION}
      - RDS_POSTGRESQL_PASSWORD=${RDS_POSTGRESQL_PASSWORD}
